### PR TITLE
Upgrade webp, libvips + include poppler

### PR DESCRIPTION
**Pull request by leaanthony**
PDF support and updates to the library versions.

### CODE REVIEW

**Comment by jcupitt** [comment]
Hiya, looks good, though the danger of poppler is that it's GPL, so if you link it into your project, your whole project becomes GPL too. This makes it unsuitable for some commercial applications.

git master libvips has a fixed-up PDFium loader. If you need PDF support, it might be worth looking at that --- PDFium has a very liberal licence.

**Comment by leaanthony** [comment]
Do you have any suggestions on how to use that instead of poppler in the given Dockerfile?

**Comment by jcupitt** [comment]
There are some notes in the code:

https://github.com/libvips/libvips/blob/master/libvips/foreign/pdfiumload.c#L50-L79

Or in the issues which tracked fixing PDFium build.

**Comment by jcupitt** [comment]
... I added those notes to the PDFium section in the main README.

**Comment by jcupitt** [comment]
Sorry @leaanthony, this slipped my mind :(

**Pull request merged**
